### ISSUE TITLE
Eit inject explosion with systemd on arm

### ISSUE THREAD

**Issue by geaaru** [Sabayon/entropy#64]
```
╠  * [core-arm] adding package: systemd-239-r1.tbz2Traceback (most recent call last):
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6924, in add_packages_to_repository
    repository_id, package_filepaths, inject = inject)
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6146, in _package_injector
    restricted_callback = _package_injector_check_restricted)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1428, in extract_package_metadata
    extract_path = pkg_dir, catch_empty = False)
  File "/usr/lib/entropy/lib/entropy/tools.py", line 2159, in uncompress_tarball
    for tarinfo in tar:
  File "/usr/lib/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python2.7/tarfile.py", line 1254, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 8: invalid start byte
```

**Comment by geaaru** [comment]
I reproduce this on amd64 with py2.7. It seems a python issue. With py3.6 (at least on amd64) works fine.
I try to upgrade to py3.6 also for ARM arch.

**Comment by Enlik** [comment]
Confirmed with sys-apps/systemd-239-r2.tbz2 built for amd64.

**Comment by Enlik** [comment]
…with Python 3 actually. And on Entropy with my changes, but they shouldn't matter.

**Comment by Enlik** [comment]
Oops, only with Python 2. Got something else with 3; ignore.

**Comment by Enlik** [comment]
* The package uses the "pax" tar format.
* The problem is with the entries:

filename|item(s)
-----------|--------
./var/log/journal|SCHILY.xattr.system.posix_acl_default, SCHILY.xattr.system.posix_acl_access
./var/log/journal/remote|SCHILY.xattr.system.posix_acl_default, SCHILY.xattr.system.posix_acl_access
./var/log/journal/remote/.keep_sys-apps_systemd-0|SCHILY.xattr.system.posix_acl_access

which cannot be decoded as utf8.
* Tarfile from Python 2.7 cannot cope with that.

**Comment by Enlik** [comment]
It was likely fixed with https://bugs.python.org/issue8633 ("tarfile doesn't support undecodable filename in PAX format"), commit https://github.com/python/cpython/commit/1465cc2887be2054cca50c72ef804adcc15fdf65, not for Python 2.

**Comment by mudler** [comment]
This still seems to happen, just tried to build a devel-9999 with latest systemd:

```
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6924, in add_packages_to_repository
    repository_id, package_filepaths, inject = inject)
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6146, in _package_injector
    restricted_callback = _package_injector_check_restricted)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1428, in extract_package_metadata
    extract_path = pkg_dir, catch_empty = False)
  File "/usr/lib/entropy/lib/entropy/tools.py", line 2159, in uncompress_tarball
    for tarinfo in tar:
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_1732039258358422034.log to /
  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_1848100961137291949.log to /
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1254, in fromtarfile
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_191997055068047544.log to /
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 8: invalid start byte
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_1929157605229474541.log to /
[2K[31m☢ [39;49;00m[01m !!! [39;49;00m ([31;01m1[39;49;00m/[34;01m2[39;49;00m) [[32mdevel-9999[39;49;00m] [31mException caught, closing tasks[39;49;00m: [32m'utf8' codec can't decode byte 0xff in position 8: invalid start byte[39;49;00m
[2K[32m╠ [39;49;00m[33m @@ [39;49;00m[[34;01mdevel-9999[39;49;00m|[31;01mrepository[39;49;00m] [34;01msyncing package sets[39;49;00m
[2K[33m☛ [39;49;00m[33m * [39;49;00m[[33mdevel-9999[39;49;00m] [32mmirrors have not been unlocked. Sync them.[39;49;00m
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_2213984450073970570.log to /
Traceback (most recent call last):
  File "/usr/bin/eit", line 18, in <module>
    main()
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_235987197571453179.log to /
  File "/usr/lib/entropy/server/eit/main.py", line 114, in main
    exit_st = func(*func_args)
  File "/usr/lib/entropy/server/eit/commands/command.py", line 237, in _call_exclusive
    return func(server)
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_2834592361934405894.log to /
  File "/usr/lib/entropy/server/eit/commands/inject.py", line 130, in _inject
    repository_id, etp_pkg_files, ask=self._ask)
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6924, in add_packages_to_repository
    repository_id, package_filepaths, inject = inject)
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_304750152795847590.log to /
  File "/usr/lib/entropy/lib/entropy/server/interfaces/main.py", line 6146, in _package_injector
    restricted_callback = _package_injector_check_restricted)
  File "/usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 1428, in extract_package_metadata
    extract_path = pkg_dir, catch_empty = False)
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_4899683666357716324.log to /
  File "/usr/lib/entropy/lib/entropy/tools.py", line 2159, in uncompress_tarball
    for tarinfo in tar:
  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_4919052127338644386.log to /
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1254, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 8: invalid start byte
Frame main in /usr/lib/entropy/server/eit/main.py at line 114
	           func_args = [<bound method EitInject._inject of <eit.commands.inject.EitInject object at 0x7f49d50c2990>>, u'devel-9999']
	                args = [u'--to', u'devel-9999', u'--quick', u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2', u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2']
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_5777402898493727829.log to /
	         _to_unicode = <function _to_unicode at 0x7f49c6c5a5f0>
	            args_map = {'status': <class 'eit.commands.status.EitStatus'>, 'ci': <class 'eit.commands.commit.EitCommit'>, 'own': <class 'eit.commands.own.EitOwn'>, 'co': <class 'eit.commands.checkout.EitCheckout'>, 'cn': <class 'eit.commands.cleanup.EitCleanup'>, 'bump': <class 'eit.commands.bump.EitBump'>, 'lock': <class 'eit.commands.lock.EitLock'>, 'sync': <class 'eit.commands.push.EitPush'>, 'unlock': <class 'eit.commands.lock.EitUnlock'>, 'query': <class 'eit.commands.query.EitQuery'>, 'cp': <class 'eit.commands.cp.EitCp'>, 'help': <class 'eit.commands.help.EitHelp'>, 'rp': <class 'eit.commands.repack.EitRepack'>, 'log': <class 'eit.commands.log.EitLog'>, 'fit': <class 'eit.commands.inject.EitInject'>, 'graph': <class 'eit.commands.graph.EitGraph'>, '-h': <class 'eit.commands.help.EitHelp'>, 'add': <class 'eit.commands.add.EitAdd'>, 'cleanup': <class 'eit.commands.cleanup.EitCleanup'>, 'inject': <class 'eit.commands.inject.EitInject'>, 'branch': <class 'eit.commands.branch.EitBranch'>, 'test': <class 'eit.commands.test.EitTest'>, 'rm': <class 'eit.commands.remove.EitRemove'>, 'checkout': <class 'eit.commands.checkout.EitCheckout'>, 'match': <class 'eit.commands.match.EitMatch'>, 'files': <class 'eit.commands.files.EitFiles'>, 'notice': <class 'eit.commands.notice.EitNotice'>, 'deps': <class 'eit.commands.deps.EitDeps'>, 'repo': <class 'eit.commands.repo.EitRepo'>, 'pkgmove': <class 'eit.commands.pkgmove.EitPkgmove'>, 'key': <class 'eit.commands.key.EitKey'>, 'vacuum': <class 'eit.commands.cleanup.EitVacuum'>, 'revgraph': <class 'eit.commands.revgraph.EitRevgraph'>, 'reset': <class 'eit.commands.reset.EitReset'>, 'pull': <class 'eit.commands.pull.EitPull'>, 'search': <class 'eit.commands.search.EitSearch'>, 'init': <class 'eit.commands.init.EitInit'>, 'remote': <class 'eit.commands.remote.EitRemote'>, 'f': <class 'eit.commands.files.EitFiles'>, 'repack': <class 'eit.commands.repack.EitRepack'>, 'list': <class 'eit.commands.list.EitList'>, 'remove': <class 'eit.commands.remove.EitRemove'>, 'st': <class 'eit.commands.status.EitStatus'>, 'q': <class 'eit.commands.query.EitQuery'>, 'merge': <class 'eit.commands.merge.EitMerge'>, 'mv': <class 'eit.commands.mv.EitMv'>, 'clean': <class 'eit.commands.cleanup.EitCleanup'>, 'push': <class 'eit.commands.push.EitPush'>, 'commit': <class 'eit.commands.commit.EitCommit'>, '--help': <class 'eit.commands.help.EitHelp'>}
	             cmd_obj = <eit.commands.inject.EitInject object at 0x7f49d50c2990>
	                 cmd = u'inject'
	           cmd_class = <class 'eit.commands.inject.EitInject'>
	          descriptor = <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c5e090>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_6160167364761276838.log to /
	         is_bashcomp = False
	           catch_all = <class 'eit.commands.help.EitHelp'>
	               alias = 'co'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_6869529333847372028.log to /
	               klass = <class 'eit.commands.checkout.EitCheckout'>
	                func = <bound method EitInject._call_exclusive of <eit.commands.inject.EitInject object at 0x7f49d50c2990>>
	             allowed = True
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_7103494537987228721.log to /
	            last_arg = u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2'
	         descriptors = [<eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c95b5910>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c81510>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c815d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c819d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c8c450>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c8ca50>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c8ce90>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c8ced0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9d550>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9d790>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9d990>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9da90>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9df10>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c9dfd0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca9210>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca9450>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca96d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca9f50>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca9e10>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6ca9f90>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6cba2d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6cba4d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6cba7d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6cba910>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6cbad90>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c444d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c44850>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c448d0>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c44c10>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c44e10>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51110>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51310>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51590>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51950>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51b50>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c51d90>, <eit.commands.descriptor.EitCommandDescriptor object at 0x7f49c6c5e090>]
Frame _call_exclusive in /usr/lib/entropy/server/eit/commands/command.py at line 242
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_8203186432472453942.log to /
	        server_class = <class 'entropy.server.interfaces.main.Server'>
	            acquired = True
	                lock = <entropy.locks.EntropyResourcesLock object at 0x7f49d50c2950>
	                self = <eit.commands.inject.EitInject object at 0x7f49d50c2990>
	              server = <entropy.server.interfaces.main.Server object at 0x7f49c7527c10>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_8281913592969493132.log to /
	                repo = u'devel-9999'
	                func = <bound method EitInject._inject of <eit.commands.inject.EitInject object at 0x7f49d50c2990>>
	           skip_lock = False
Frame _inject in /usr/lib/entropy/server/eit/commands/inject.py at line 130
	       repository_id = u'devel-9999'
	      entropy_server = <entropy.server.interfaces.main.Server object at 0x7f49c7527c10>
	                self = <eit.commands.inject.EitInject object at 0x7f49d50c2990>
	       etp_pkg_files = [([u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'], True), ([u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2'], True)]
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_8744906478815150044.log to /
	                 ext = 'tbz2'
	          extensions = ['tbz2']
	                   x = u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2'
	            pkg_path = u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/build_93715524680565111.log to /
	               found = True
Frame add_packages_to_repository in /usr/lib/entropy/lib/entropy/server/interfaces/main.py at line 6949
	               count = (1, 2)
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/PKGLIST-amd64 to /devel-9999/
	       repository_id = u'devel-9999'
	    package_filepath = u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/.packages.db.lock.lock to /devel-9999/standard/devel-9999/database/amd64/5/
	                 err = UnicodeDecodeError('utf8', '\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff\x08\x00\x05\x00\x04\x00\x00\x00\x08\x00\x05\x00\n\x00\x00\x00\x10\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff', 8, 9, 'invalid start byte')
	      to_be_injected = set([])
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/ChangeLog.bz2 to /devel-9999/standard/devel-9999/database/amd64/5/
	                self = <entropy.server.interfaces.main.Server object at 0x7f49c7527c10>
	              header = '\x1b[34;01m @@ \x1b[39;49;00m'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.bz2 to /devel-9999/standard/devel-9999/database/amd64/5/
	              inject = True
	            maxcount = 2
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.bz2.md5 to /devel-9999/standard/devel-9999/database/amd64/5/
	                 ask = False
	   package_ids_added = set([])
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.dumplight.bz2 to /devel-9999/standard/devel-9999/database/amd64/5/
	       packages_data = [([u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'], True), ([u'/tmp/tmp.wzFfoV1J7G/sabayon-live-9999.tbz2'], True)]
	             mycount = 1
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.dumplight.bz2.md5 to /devel-9999/standard/devel-9999/database/amd64/5/
	   package_filepaths = [u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2']
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.eapi3_updates to /devel-9999/standard/devel-9999/database/amd64/5/
Frame _package_injector in /usr/lib/entropy/lib/entropy/server/interfaces/main.py at line 6146
	       repository_id = u'devel-9999'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.extra_pkglist to /devel-9999/standard/devel-9999/database/amd64/5/
	       package_files = [u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2']
	             srv_set = {'default_repository_id': u'devel-9999', 'weak_package_files': False, 'qa_langs': [u'en_US', u'C'], 'packages_expiration_days': 15, 'rss': {'max_entries': 10000, 'light_name': u'updates.rss', 'name': u'packages.rss', 'light_max_entries': 300, 'enabled': True, 'base_url': u'http://packages.sabayon.org/?quicksearch=', 'website_url': u'http://www.sabayon.org/', 'editor': u'lxnay@sabayon.org'}, 'broken_revdeps_qa_check': False, 'changelog': True, 'sync_speed_limit': None, 'database_file_format': u'bz2', 'repositories': {u'devel-9999': {'description': u'Devel-9999 channel repository', 'upload_basedir': u'/var/lib/entropy/server/devel-9999/upload', 'community': True, 'exclude_qa': False, 'store_dir': u'/var/lib/entropy/server/devel-9999/store/amd64', 'remote_repo_basedir': u'standard/devel-9999', 'packages_dir_nonfree': u'/var/lib/entropy/server/devel-9999/packages-nonfree/amd64', 'database_remote_path': u'standard/devel-9999/database/amd64', 'repoid': u'devel-9999', 'database_dir': u'/var/lib/entropy/server/devel-9999/database/amd64', 'repo_mirrors': [u'file://///var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999'], 'pkg_mirrors': [u'file://///var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999'], 'override_database_remote_path': None, 'repo_basedir': u'/var/lib/entropy/server/devel-9999', 'packages_dir_restricted': u'/var/lib/entropy/server/devel-9999/packages-restricted/amd64', 'packages_dir': u'/var/lib/entropy/server/devel-9999/packages/amd64'}, '__system__': {'database_dir': '/var/lib/entropy/server/__system__/database/amd64', 'description': u'Community Repositories System Repository', 'repo_mirrors': [], 'packages_dir_nonfree': '/var/lib/entropy/server/__system__/packages-nonfree/amd64', 'pkg_mirrors': [], 'community': True, 'upload_basedir': '/var/lib/entropy/server/__system__/upload', 'exclude_qa': False, 'store_dir': '/var/lib/entropy/server/__system__/store/amd64', 'remote_repo_basedir': u'standard/__system__', 'override_database_remote_path': None, 'repo_basedir': '/var/lib/entropy/server/__system__', 'database_remote_path': u'standard/__system__/database/amd64', 'repoid': '__system__', 'packages_dir_restricted': '/var/lib/entropy/server/__system__/packages-restricted/amd64', 'packages_dir': '/var/lib/entropy/server/__system__/packages/amd64'}}, 'disabled_eapis': set([]), 'exp_based_scope': False, 'nonfree_packages_dir_support': False, 'base_repository_id': '__system__', 'community_mode': True}
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.light.bz2 to /devel-9999/standard/devel-9999/database/amd64/5/
	                self = <entropy.server.interfaces.main.Server object at 0x7f49c7527c10>
	_package_injector_check_restricted = <function _package_injector_check_restricted at 0x7f49c4d43848>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.light.bz2.md5 to /devel-9999/standard/devel-9999/database/amd64/5/
	              inject = True
	_package_injector_check_license = <function _package_injector_check_license at 0x7f49c6c5ab90>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.md5 to /devel-9999/standard/devel-9999/database/amd64/5/
	              dbconn = <EntropySQLiteRepository instance at 0x7f49c6c21090, /var/lib/entropy/server/devel-9999/database/amd64/5/packages.db, ro: False|False, caching: False, indexing: True, name: devel-9999, skip_upd: False, conn_pool: {}, cursor_cache: {}>
	        package_file = u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.meta to /devel-9999/standard/devel-9999/database/amd64/5/
Frame extract_package_metadata in /usr/lib/entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py at line 1430
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.pkglist to /devel-9999/standard/devel-9999/database/amd64/5/
	             tmp_dir = u'/var/tmp/entropy/entropy.spm._extract3iHfjy'
	             pkg_dir = u'/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.revision to /devel-9999/standard/devel-9999/database/amd64/5/
	                self = <entropy.spm.plugins.interfaces.portage_plugin.PortagePlugin object at 0x7f49c6c0b610>
	       empty_content = False
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.timestamp to /devel-9999/standard/devel-9999/database/amd64/5/
	    license_callback = <function _package_injector_check_license at 0x7f49c6c5ab90>
	 restricted_callback = <function _package_injector_check_restricted at 0x7f49c4d43848>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.db.webinst_updates to /devel-9999/standard/devel-9999/database/amd64/5/
	     system_settings = <entropy.core.settings.base.SystemSettings object at 0x7f49c7515d90>
	                data = {'datecreation': '1542398909.19', 'signatures': {'sha256': '2e147b8eef6232c4bbf38d7dccf509eb081278958bfc3b7cd0c20126897d5731', 'gpg': None, 'sha1': '02681bc46834cfe0c7bd4cb033955ae1fdfb3115', 'sha512': '271fd5ec439eda598834581de22866c7f7c9e43b598d04521f28197228855905f8e9cdf9b95e16218756e8fd60faedcaa6363d361239570502ff9c56c85bd6ba'}, 'digest': 'b88483a9e402f3d989250d5d91293835', 'size': '6693389'}
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/packages.rss to /devel-9999/standard/devel-9999/database/amd64/5/
	        package_file = u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'
	            meta_dir = u'/var/tmp/entropy/entropy.spm._extract3iHfjy/portage'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/database/amd64/5/updates.rss to /devel-9999/standard/devel-9999/database/amd64/5/
Frame uncompress_tarball in /usr/lib/entropy/lib/entropy/tools.py at line 2214
	         is_python_3 = False
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999/standard/devel-9999/packages/amd64/5/app-misc/app-misc:sabayon-live-9999.5755301bcd227bd32b61204903d64278ff41feaa~1.tbz2 to /devel-9999/standard/devel-9999/packages/amd64/5/app-misc/
	        encoded_path = '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg'
	                 tar = <tarfile.TarFile object at 0x7f49c4b4ec10>
	            filepath = u'/tmp/tmp.wzFfoV1J7G/systemd-239-r2.tbz2'
	               epath = '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./var/log'
	     deleter_counter = 3
	_setup_file_metadata = <function _setup_file_metadata at 0x7f49c495c050>
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999-binhost/Packages to /devel-9999-binhost/
	             entries = [(<TarInfo '.' at 0x7f49c4b4ea10>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/.'), (<TarInfo './etc' at 0x7f49c4b4eb90>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc'), (<TarInfo './etc/modprobe.d' at 0x7f49c4b4ec90>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/modprobe.d'), (<TarInfo './etc/pam.d' at 0x7f49c4b4e990>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/pam.d'), (<TarInfo './etc/systemd' at 0x7f49c4b4ec50>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd'), (<TarInfo './etc/systemd/network' at 0x7f49c4b4e690>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/network'), (<TarInfo './etc/systemd/user' at 0x7f49c4b4eb50>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/user'), (<TarInfo './etc/systemd/ntp-units.d' at 0x7f49c4b4e710>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/ntp-units.d'), (<TarInfo './etc/systemd/system' at 0x7f49c4b4e9d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system'), (<TarInfo './etc/systemd/system/multi-user.target.wants' at 0x7f49c4b4efd0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/multi-user.target.wants'), (<TarInfo './etc/systemd/system/multi-user.target.wants/remote-cryptsetup.target' at 0x7f49c4b4ee90>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/multi-user.target.wants/remote-cryptsetup.target'), (<TarInfo './etc/systemd/system/multi-user.target.wants/machines.target' at 0x7f49c4b4ead0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/multi-user.target.wants/machines.target'), (<TarInfo './etc/systemd/system/multi-user.target.wants/remote-fs.target' at 0x7f49c4b4e950>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/multi-user.target.wants/remote-fs.target'), (<TarInfo './etc/systemd/system/getty.target.wants' at 0x7f49c4b4e8d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/getty.target.wants'), (<TarInfo './etc/systemd/system/getty.target.wants/getty@tty1.service' at 0x7f49c4b4e1d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/systemd/system/getty.target.wants/getty@tty1.service'), (<TarInfo './etc/tmpfiles.d' at 0x7f49c4b4e190>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/tmpfiles.d'), (<TarInfo './etc/X11' at 0x7f49c4b4e110>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/X11'), (<TarInfo './etc/X11/xinit' at 0x7f49c4b4e150>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/X11/xinit'), (<TarInfo './etc/X11/xinit/xinitrc.d' at 0x7f49c4b4ee10>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/X11/xinit/xinitrc.d'), (<TarInfo './etc/binfmt.d' at 0x7f49c4b4e590>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/binfmt.d'), (<TarInfo './etc/udev' at 0x7f49c4b4e550>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/udev'), (<TarInfo './etc/udev/hwdb.d' at 0x7f49c4b4e5d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/udev/hwdb.d'), (<TarInfo './etc/udev/rules.d' at 0x7f49c4b4e210>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/udev/rules.d'), (<TarInfo './etc/xdg' at 0x7f49c4b4e4d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/xdg'), (<TarInfo './etc/xdg/systemd' at 0x7f49c4b4e510>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/xdg/systemd'), (<TarInfo './etc/xdg/systemd/user' at 0x7f49c4b4e050>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/xdg/systemd/user'), (<TarInfo './etc/sysctl.d' at 0x7f49c4b4e450>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/sysctl.d'), (<TarInfo './etc/sysctl.d/99-sysctl.conf' at 0x7f49c4b4e410>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/sysctl.d/99-sysctl.conf'), (<TarInfo './etc/kernel' at 0x7f49c4b4e3d0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/kernel'), (<TarInfo './etc/kernel/install.d' at 0x7f49c4b4e390>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/kernel/install.d'), (<TarInfo './etc/modules-load.d' at 0x7f49c4b4e350>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./etc/modules-load.d'), (<TarInfo './var' at 0x7f49c4f7acd0>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./var'), (<TarInfo './var/lib' at 0x7f49c4f7ac50>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./var/lib'), (<TarInfo './var/lib/systemd' at 0x7f49c4b4e090>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./var/lib/systemd'), (<TarInfo './var/log' at 0x7f49c4f7ac90>, '/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg/./var/log')]
	         catch_empty = False
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999-binhost/app-misc/sabayon-live-9999.tbz2 to /devel-9999-binhost/app-misc/
	 extracted_something = True
	        extract_path = u'/var/tmp/entropy/entropy.spm._extract3iHfjy/pkg'
Uploading /var/lib/docker/build/583945716035976567/devel-9999/artifacts/devel-9999-binhost/sys-apps/systemd-239-r2.tbz2 to /devel-9999-binhost/sys-apps/
	             tarinfo = <TarInfo './var/log' at 0x7f49c4f7ac90>
Frame next in /usr/lib64/python2.7/tarfile.py at line 2510
	                self = <tarfile.TarIter instance at 0x7f49c5287248>
Frame next in /usr/lib64/python2.7/tarfile.py at line 2378
	                self = <tarfile.TarFile object at 0x7f49c4b4ec10>
	             tarinfo = None
Frame fromtarfile in /usr/lib64/python2.7/tarfile.py at line 1254
	                 buf = './var/log/PaxHeaders.16114/journal\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000000644\x000000000\x000000000\x0000000000425\x0013373621415\x00013724\x00 x\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ustar\x0000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	             tarfile = <tarfile.TarFile object at 0x7f49c4b4ec10>
	                 obj = <TarInfo './var/log/PaxHeaders.16114/journal' at 0x7f49c4b4e250>
	                 cls = <class 'tarfile.TarInfo'>
Frame _proc_member in /usr/lib64/python2.7/tarfile.py at line 1276
	                self = <TarInfo './var/log/PaxHeaders.16114/journal' at 0x7f49c4b4e250>
	             tarfile = <tarfile.TarFile object at 0x7f49c4b4ec10>
Frame _proc_pax in /usr/lib64/python2.7/tarfile.py at line 1406
	               regex = <_sre.SRE_Pattern object at 0x7f49c4d35940>
	             keyword = u'SCHILY.xattr.system.posix_acl_default'
	                self = <TarInfo './var/log/PaxHeaders.16114/journal' at 0x7f49c4b4e250>
	         pax_headers = {u'atime': u'1542398734.386883461', u'ctime': u'1542398733.473859312', u'mtime': u'1542398733.473859312'}
	             tarfile = <tarfile.TarFile object at 0x7f49c4b4ec10>
	                 pos = 90
	               value = '\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff\x08\x00\x05\x00\x04\x00\x00\x00\x08\x00\x05\x00\n\x00\x00\x00\x10\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff'
	              length = 94
	                 buf = '30 mtime=1542398733.473859312\n30 atime=1542398734.386883461\n30 ctime=1542398733.473859312\n94 SCHILY.xattr.system.posix_acl_default=\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff\x08\x00\x05\x00\x04\x00\x00\x00\x08\x00\x05\x00\n\x00\x00\x00\x10\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff\n93 SCHILY.xattr.system.posix_acl_access=\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff\x08\x00\x05\x00\x04\x00\x00\x00\x08\x00\x05\x00\n\x00\x00\x00\x10\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	               match = <_sre.SRE_Match object at 0x7f49c4988cf0>
Frame decode in /usr/lib64/python2.7/encodings/utf_8.py at line 16
	               input = '\x02\x00\x00\x00\x01\x00\x07\x00\xff\xff\xff\xff\x04\x00\x05\x00\xff\xff\xff\xff\x08\x00\x05\x00\x04\x00\x00\x00\x08\x00\x05\x00\n\x00\x00\x00\x10\x00\x05\x00\xff\xff\xff\xff \x00\x05\x00\xff\xff\xff\xff'
	              errors = 'strict'
ouch unable to inject
```

**Comment by mudler** [comment]
Let it open to keep track of it, I still see it during builds
